/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lz_ffmpeg_FFmpegNativeUtil */

#ifndef _Included_com_example_lz_ffmpeg_FFmpegNativeUtil
#define _Included_com_example_lz_ffmpeg_FFmpegNativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lz_ffmpeg_FFmpegNativeUtil
 * Method:    videoStreamPlay
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_example_lz_ffmpeg_FFmpegNativeUtil_videoStreamPlay
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
